# CPack configuration for NSIS installer generation

include_guard(GLOBAL)

set(CPACK_GENERATOR "NSIS")
set(CPACK_PACKAGE_NAME "${CMAKE_PROJECT_NAME}")
set(CPACK_PACKAGE_VERSION "${PLUGIN_VERSION}")
set(CPACK_PACKAGE_VERSION_MAJOR "${PLUGIN_VERSION_MAJOR}")
set(CPACK_PACKAGE_VERSION_MINOR "${PLUGIN_VERSION_MINOR}")
set(CPACK_PACKAGE_VERSION_PATCH "${PLUGIN_VERSION_PATCH}")
set(CPACK_PACKAGE_VENDOR "${PLUGIN_AUTHOR}")
set(CPACK_PACKAGE_DESCRIPTION_SUMMARY "OBS Studio plugin for scene lighting")
set(CPACK_PACKAGE_HOMEPAGE_URL "${PLUGIN_WEBSITE}")
set(CPACK_PACKAGE_INSTALL_DIRECTORY "obs-scene-lighting")
set(CPACK_RESOURCE_FILE_LICENSE "${CMAKE_CURRENT_SOURCE_DIR}/LICENSE")
set(CPACK_PACKAGE_FILE_NAME "${CMAKE_PROJECT_NAME}-${PLUGIN_VERSION}-windows-x64")

set(CPACK_NSIS_DISPLAY_NAME "Scene Lighting for OBS")
set(CPACK_NSIS_PACKAGE_NAME "obs-scene-lighting")
set(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES64\\\\obs-studio")
set(CPACK_NSIS_ENABLE_UNINSTALL_BEFORE_INSTALL ON)
set(CPACK_NSIS_MODIFY_PATH OFF)

include("${CMAKE_ROOT}/Modules/CPack.cmake")
