<#
.SYNOPSIS
  Clean build artifacts for obs-scene-lighting.

.DESCRIPTION
  Removes build artifacts selectively based on the Target parameter:

    Dev   - Removes the entire CMake build directory (build_x64/ by default).
            Use this when you want a full reconfigure and rebuild from scratch.

    Dist  - Removes only the packaged distribution artifacts: the CPack-generated
            NSIS installer (.exe) and the install/ staging directory inside the
            build directory. Compiled object files and CMake cache are preserved.

    All   - Performs both Dev and Dist cleanup.

.PARAMETER Target
  What to clean. One of: Dev, Dist, All. Defaults to All.

.PARAMETER BuildDir
  Path to the CMake build directory, relative to the repository root.
  Defaults to 'build_x64'.

.PARAMETER DryRun
  Show what would be removed without deleting anything.

.EXAMPLE
  .\scripts\clean.ps1
  .\scripts\clean.ps1 -Target Dev
  .\scripts\clean.ps1 -Target Dist
  .\scripts\clean.ps1 -Target All -DryRun
#>
[CmdletBinding(SupportsShouldProcess)]
param(
  [ValidateSet("Dev", "Dist", "All")]
  [string]$Target = "All",
  [string]$BuildDir = "build_x64",
  [switch]$DryRun
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

$repoRoot = Split-Path -Parent $PSScriptRoot
$resolvedBuildDir = Join-Path $repoRoot $BuildDir

function Remove-ItemIfExists {
  param(
    [string]$Path,
    [string]$Label
  )

  if (-not (Test-Path $Path)) {
    Write-Host "  Not found, skipping: $Path" -ForegroundColor DarkGray
    return
  }

  if ($DryRun) {
    Write-Host "  DRY RUN: Remove $Label -> $Path" -ForegroundColor DarkYellow
    return
  }

  if ($PSCmdlet.ShouldProcess($Path, "Remove $Label")) {
    Remove-Item -Recurse -Force $Path
    Write-Host "  Removed: $Path" -ForegroundColor Green
  }
}

Write-Host "Clean: obs-scene-lighting [Target=${Target}]" -ForegroundColor Cyan
Write-Host "Build directory: ${resolvedBuildDir}" -ForegroundColor Gray

# --- Dev: Remove the entire CMake build directory ---

if ($Target -eq "Dev" -or $Target -eq "All") {
  Write-Host "`n[Dev] Removing CMake build directory..." -ForegroundColor Yellow
  Remove-ItemIfExists -Path $resolvedBuildDir -Label "CMake build directory"
}

# --- Dist: Remove CPack installer and install/ staging directory ---

if ($Target -eq "Dist" -or $Target -eq "All") {
  Write-Host "`n[Dist] Removing distribution artifacts..." -ForegroundColor Yellow

  # Remove the install/ staging directory created by cmake --install
  $installDir = Join-Path $resolvedBuildDir "install"
  Remove-ItemIfExists -Path $installDir -Label "install staging directory"

  # Remove NSIS installers generated by CPack
  $installers = Get-ChildItem -Path $resolvedBuildDir -Filter "obs-scene-lighting-*.exe" -ErrorAction SilentlyContinue
  if ($installers) {
    foreach ($installer in $installers) {
      Remove-ItemIfExists -Path $installer.FullName -Label "NSIS installer"
    }
  } else {
    Write-Host "  No NSIS installers found, skipping." -ForegroundColor DarkGray
  }
}

Write-Host "`nClean complete." -ForegroundColor Cyan
